# Structure Learning in Bayesian Networks

In this notebook, we show a few examples of Causal Discovery or Structure Learning in pgmpy. pgmpy currently has the following algorithm for causal discovery:

1. **PC**: Has $3$ variants original, stable, and parallel. PC is a constraint-based algorithm that utilizes Conditional Independence tests to construct the model.
2. **Hill-Climb Search**: Hill-Climb Search is a greedy optimization-based algorithm that makes iterative local changes to the model structure such that it improves the overall score of the model.
3. **Exhaustive Search**: Exhaustive search iterates over all possible network structures on the given variables to find the most optimal one. As it tries to enumerate all possible network structures, it is intractable when the number of variables in the data is large.

The following Conditional Independence Tests are available to use with the PC algorithm:
1. **Pillai**: Test for mixed data based on residualization approach. It is a generalization of Pearsonr to mixed data.
1. **Chi-Square test**: Works only for discrete data.
2. **Pearsonr**: A partial correlation-based test. Works for Gaussian continuous variables.
3. **G-squared**: Works only for discrete data.
4. **Log-likelihood**: Works only for discrete data.

For Hill-Climb and Exhausitive Search the following scoring methods can be used:
1. **BIC Score**
2. **AIC Score**
3. **K2 Score**
4. **BDeU Score**
5. **BDs Score**

## Generate some data with a Discrete Bayesian Network
We start with an example model with discrete valued variables.

In [2]:
from itertools import combinations

import networkx as nx
from sklearn.metrics import f1_score

from pgmpy.estimators import PC, HillClimbSearch, ExhaustiveSearch
from pgmpy.estimators import K2
from pgmpy.utils import get_example_model
import numpy as np

In [3]:
model = get_example_model("alarm")
samples = model.simulate(int(1e3))
samples.head()

Generating for node: BP:   0%|          | 0/37 [00:00<?, ?it/s]          WARNING:pgmpy:Probability values don't exactly sum to 1. Differ by: -2.220446049250313e-16. Adjusting values.
Generating for node: BP: 100%|██████████| 37/37 [00:00<00:00, 1015.26it/s]

,EXPCO2,MINVOLSET,BP,CATECHOL,INSUFFANESTH,PULMEMBOLUS,VENTTUBE,HRBP,CVP,KINKEDTUBE,...,MINVOL,HRSAT,HYPOVOLEMIA,PRESS,VENTMACH,VENTALV,ERRCAUTER,LVEDVOLUME,VENTLUNG,ANAPHYLAXIS
0,HIGH,NORMAL,LOW,HIGH,TRUE,FALSE,NORMAL,LOW,NORMAL,FALSE,...,LOW,LOW,FALSE,HIGH,NORMAL,LOW,FALSE,NORMAL,HIGH,FALSE
1,ZERO,NORMAL,HIGH,HIGH,FALSE,FALSE,LOW,HIGH,NORMAL,FALSE,...,LOW,NORMAL,FALSE,HIGH,NORMAL,NORMAL,TRUE,NORMAL,LOW,FALSE
2,LOW,NORMAL,HIGH,HIGH,FALSE,FALSE,LOW,HIGH,HIGH,FALSE,...,ZERO,HIGH,FALSE,HIGH,NORMAL,ZERO,FALSE,HIGH,ZERO,FALSE
3,LOW,NORMAL,HIGH,HIGH,FALSE,FALSE,LOW,HIGH,NORMAL,FALSE,...,ZERO,NORMAL,FALSE,HIGH,NORMAL,ZERO,TRUE,NORMAL,ZERO,FALSE
4,LOW,NORMAL,LOW,HIGH,FALSE,FALSE,LOW,LOW,NORMAL,FALSE,...,ZERO,NORMAL,FALSE,HIGH,NORMAL,ZERO,FALSE,NORMAL,ZERO,FALSE

In [4]:
# Function to evaluate the learned model structures.
def get_f1_score(estimated_model, true_model):
    nodes = estimated_model.nodes()
    est_adj = nx.to_numpy_array(
        estimated_model.to_undirected(), nodelist=nodes, weight=None
    )
    true_adj = nx.to_numpy_array(
        true_model.to_undirected(), nodelist=nodes, weight=None
    )

    f1 = f1_score(np.ravel(true_adj), np.ravel(est_adj))
    print("F1-score for the model skeleton: ", f1)

## Learn the model structure using PC for a Discrete Bayesian Network
For `PC` algorithm, the statistical test `ci_test` is by default `chi_square`, which is suitable for discrete data.

In [5]:
est = PC(data=samples)
estimated_model = est.estimate(variant="stable", max_cond_vars=4)
get_f1_score(estimated_model, model)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'EXPCO2': 'C', 'MINVOLSET': 'C', 'BP': 'C', 'CATECHOL': 'C', 'INSUFFANESTH': 'C', 'PULMEMBOLUS': 'C', 'VENTTUBE': 'C', 'HRBP': 'C', 'CVP': 'C', 'KINKEDTUBE': 'C', 'PCWP': 'C', 'SHUNT': 'C', 'INTUBATION': 'C', 'SAO2': 'C', 'FIO2': 'C', 'LVFAILURE': 'C', 'PAP': 'C', 'DISCONNECT': 'C', 'PVSAT': 'C', 'ARTCO2': 'C', 'HREKG': 'C', 'STROKEVOLUME': 'C', 'HR': 'C', 'ERRLOWOUTPUT': 'C', 'CO': 'C', 'TPR': 'C', 'HISTORY': 'C', 'MINVOL': 'C', 'HRSAT': 'C', 'HYPOVOLEMIA': 'C', 'PRESS': 'C', 'VENTMACH': 'C', 'VENTALV': 'C', 'ERRCAUTER': 'C', 'LVEDVOLUME': 'C', 'VENTLUNG': 'C', 'ANAPHYLAXIS': 'C'}
Working for n conditional variables: 5: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]

F1-score for the model skeleton:  0.8354430379746836

In [6]:
est = PC(data=samples)
estimated_model = est.estimate(variant="orig", max_cond_vars=4)
get_f1_score(estimated_model, model)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'EXPCO2': 'C', 'MINVOLSET': 'C', 'BP': 'C', 'CATECHOL': 'C', 'INSUFFANESTH': 'C', 'PULMEMBOLUS': 'C', 'VENTTUBE': 'C', 'HRBP': 'C', 'CVP': 'C', 'KINKEDTUBE': 'C', 'PCWP': 'C', 'SHUNT': 'C', 'INTUBATION': 'C', 'SAO2': 'C', 'FIO2': 'C', 'LVFAILURE': 'C', 'PAP': 'C', 'DISCONNECT': 'C', 'PVSAT': 'C', 'ARTCO2': 'C', 'HREKG': 'C', 'STROKEVOLUME': 'C', 'HR': 'C', 'ERRLOWOUTPUT': 'C', 'CO': 'C', 'TPR': 'C', 'HISTORY': 'C', 'MINVOL': 'C', 'HRSAT': 'C', 'HYPOVOLEMIA': 'C', 'PRESS': 'C', 'VENTMACH': 'C', 'VENTALV': 'C', 'ERRCAUTER': 'C', 'LVEDVOLUME': 'C', 'VENTLUNG': 'C', 'ANAPHYLAXIS': 'C'}
Working for n conditional variables: 5: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]

F1-score for the model skeleton:  0.8354430379746836

## Learn the model structure using Hill-Climb Search for a Discrete Bayesian Network

In [7]:
scoring_method = K2(data=samples)
est = HillClimbSearch(data=samples)
estimated_model = est.estimate(
    scoring_method=scoring_method, max_indegree=4, max_iter=int(1e4)
)
get_f1_score(estimated_model, model)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'EXPCO2': 'C', 'MINVOLSET': 'C', 'BP': 'C', 'CATECHOL': 'C', 'INSUFFANESTH': 'C', 'PULMEMBOLUS': 'C', 'VENTTUBE': 'C', 'HRBP': 'C', 'CVP': 'C', 'KINKEDTUBE': 'C', 'PCWP': 'C', 'SHUNT': 'C', 'INTUBATION': 'C', 'SAO2': 'C', 'FIO2': 'C', 'LVFAILURE': 'C', 'PAP': 'C', 'DISCONNECT': 'C', 'PVSAT': 'C', 'ARTCO2': 'C', 'HREKG': 'C', 'STROKEVOLUME': 'C', 'HR': 'C', 'ERRLOWOUTPUT': 'C', 'CO': 'C', 'TPR': 'C', 'HISTORY': 'C', 'MINVOL': 'C', 'HRSAT': 'C', 'HYPOVOLEMIA': 'C', 'PRESS': 'C', 'VENTMACH': 'C', 'VENTALV': 'C', 'ERRCAUTER': 'C', 'LVEDVOLUME': 'C', 'VENTLUNG': 'C', 'ANAPHYLAXIS': 'C'}
INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'EXPCO2': 'C', 'MINVOLSET': 'C', 'BP': 'C', 'CATECHOL': 'C', 'INSUFFANESTH': 'C', 'PULMEMBOLUS': 'C', 'VENTTUBE': 'C', 'HRBP': 'C', 'CVP': 'C', 'KINKEDTUBE': 'C', 'PCWP': 'C', 'SHUNT': 'C', 'INTUBATION': 'C', 'SAO2': 'C', 'FIO2': 'C', 'LVFAILURE': 'C', 'PAP': 'C', 'DISCONNECT': 'C', 'PVSAT': 'C', 'ARTCO2': 'C', 'HREKG': 'C', 'STROKEVOLUME': 'C', 'HR': 'C', 'ERRLOWOUTPUT': 'C', 'CO': 'C', 'TPR': 'C', 'HISTORY': 'C', 'MINVOL': 'C', 'HRSAT': 'C', 'HYPOVOLEMIA': 'C', 'PRESS': 'C', 'VENTMACH': 'C', 'VENTALV': 'C', 'ERRCAUTER': 'C', 'LVEDVOLUME': 'C', 'VENTLUNG': 'C', 'ANAPHYLAXIS': 'C'}
INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'EXPCO2': 'C', 'MINVOLSET': 'C', 'BP': 'C', 'CATECHOL': 'C', 'INSUFFANESTH': 'C', 'PULMEMBOLUS': 'C', 'VENTTUBE': 'C', 'HRBP': 'C', 'CVP': 'C', 'KINKEDTUBE': 'C', 'PCWP': 'C', 'SHUNT': 'C', 'INTUBATION': 'C', 'SAO2': 'C', 'FIO2': 'C', 'LVFAILURE': 'C', 'PAP': 'C', 'DISCONNECT': 'C', 'PVSAT': 'C', 'ARTCO2': 'C', 'HREKG': 'C', 'STROKEVOLUME': 'C', 'HR': 'C', 'ERRLOWOUTPUT': 'C', 'CO': 'C', 'TPR': 'C', 'HISTORY': 'C', 'MINVOL': 'C', 'HRSAT': 'C', 'HYPOVOLEMIA': 'C', 'PRESS': 'C', 'VENTMACH': 'C', 'VENTALV': 'C', 'ERRCAUTER': 'C', 'LVEDVOLUME': 'C', 'VENTLUNG': 'C', 'ANAPHYLAXIS': 'C'}
  1%|          | 73/10000 [00:04<10:30, 15.74it/s]

F1-score for the model skeleton:  0.7241379310344828

## Generate some data with a Gaussian Bayesian Network
The above algorithms also work for Gaussian Bayesian Networks where variables are continuous.

In [8]:
cont_model = get_example_model("ecoli70")
cont_samples = cont_model.simulate(int(1e3))
cont_samples.head()

,b1191,cspG,eutG,fixC,cspA,yecO,yedE,sucA,cchB,yceP,...,dnaK,folK,ycgX,lacZ,nuoM,dnaG,b1583,mopB,yaeM,ftsJ
0,0.596232,1.522552,1.843879,0.764435,-0.148143,-0.122119,-1.466005,-2.576103,1.910655,2.002379,...,-0.282578,1.225944,0.760629,2.225496,-1.493486,0.548432,2.208580,-0.734430,1.907569,-0.142266
1,1.810833,3.843105,1.134461,2.797687,0.197745,3.123587,-3.559714,-0.776648,2.781934,1.005793,...,1.532387,1.604336,1.109946,2.260461,-1.433214,1.327802,3.822626,1.424924,7.183388,1.320880
2,0.162407,0.909655,0.823645,0.907878,-0.210944,1.508969,-1.712000,-1.748348,1.826058,0.563026,...,-1.495990,-1.495879,-2.944550,0.865920,-1.718713,-2.122912,1.854984,-0.870632,2.034139,-0.279813
3,1.002033,2.152233,0.371009,1.982395,-0.575419,1.988091,-1.374106,0.266386,3.144987,-0.882142,...,1.271169,1.835162,2.444017,2.019385,-1.544797,1.430496,0.536170,0.992915,3.369650,2.015740
4,-0.395021,2.505254,0.161141,0.834475,-1.005705,2.469934,-2.651093,-0.399063,0.888151,0.113400,...,-1.109591,-0.441581,-1.870356,-0.181795,-1.430118,-1.425760,2.367335,-1.077882,5.590468,-0.020663

## Learn the model structure using PC for a Gaussian Bayesian Network
For continuous model, we need to use `ci_test` suitable for continuous data, such as Pearson's R.

In [9]:
cont_est = PC(data=cont_samples)
cont_estimated_model = cont_est.estimate(variant="stable", ci_test="pearsonr", max_cond_vars=4)
get_f1_score(cont_estimated_model, cont_model)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'b1191': 'N', 'cspG': 'N', 'eutG': 'N', 'fixC': 'N', 'cspA': 'N', 'yecO': 'N', 'yedE': 'N', 'sucA': 'N', 'cchB': 'N', 'yceP': 'N', 'ygbD': 'N', 'yjbO': 'N', 'yfiA': 'N', 'lpdA': 'N', 'pspB': 'N', 'atpG': 'N', 'dnaJ': 'N', 'flgD': 'N', 'gltA': 'N', 'sucD': 'N', 'tnaA': 'N', 'ygcE': 'N', 'yhdM': 'N', 'ibpB': 'N', 'yfaD': 'N', 'hupB': 'N', 'pspA': 'N', 'asnA': 'N', 'atpD': 'N', 'nmpC': 'N', 'icdA': 'N', 'lacA': 'N', 'yheI': 'N', 'aceB': 'N', 'lacY': 'N', 'b1963': 'N', 'dnaK': 'N', 'folK': 'N', 'ycgX': 'N', 'lacZ': 'N', 'nuoM': 'N', 'dnaG': 'N', 'b1583': 'N', 'mopB': 'N', 'yaeM': 'N', 'ftsJ': 'N'}
Working for n conditional variables: 5: 100%|██████████| 5/5 [00:11<00:00,  1.71s/it]INFO:pgmpy:Reached maximum number of allowed conditional variables. Exiting
Working for n conditional variables: 5: 100%|██████████| 5/5 [00:11<00:00,  2.27s/it]

F1-score for the model skeleton:  0.639344262295082

## Learn the model structure using Hill-Climb Search for a Gaussian Bayesian Network

In [10]:
cont_scoring_method = K2(data=cont_samples)
cont_est = HillClimbSearch(data=cont_samples)
cont_estimated_model = cont_est.estimate(
    scoring_method=cont_scoring_method, max_indegree=4, max_iter=int(1e2)
)
get_f1_score(cont_estimated_model, cont_model)

INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'b1191': 'N', 'cspG': 'N', 'eutG': 'N', 'fixC': 'N', 'cspA': 'N', 'yecO': 'N', 'yedE': 'N', 'sucA': 'N', 'cchB': 'N', 'yceP': 'N', 'ygbD': 'N', 'yjbO': 'N', 'yfiA': 'N', 'lpdA': 'N', 'pspB': 'N', 'atpG': 'N', 'dnaJ': 'N', 'flgD': 'N', 'gltA': 'N', 'sucD': 'N', 'tnaA': 'N', 'ygcE': 'N', 'yhdM': 'N', 'ibpB': 'N', 'yfaD': 'N', 'hupB': 'N', 'pspA': 'N', 'asnA': 'N', 'atpD': 'N', 'nmpC': 'N', 'icdA': 'N', 'lacA': 'N', 'yheI': 'N', 'aceB': 'N', 'lacY': 'N', 'b1963': 'N', 'dnaK': 'N', 'folK': 'N', 'ycgX': 'N', 'lacZ': 'N', 'nuoM': 'N', 'dnaG': 'N', 'b1583': 'N', 'mopB': 'N', 'yaeM': 'N', 'ftsJ': 'N'}
INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'b1191': 'N', 'cspG': 'N', 'eutG': 'N', 'fixC': 'N', 'cspA': 'N', 'yecO': 'N', 'yedE': 'N', 'sucA': 'N', 'cchB': 'N', 'yceP': 'N', 'ygbD': 'N', 'yjbO': 'N', 'yfiA': 'N', 'lpdA': 'N', 'pspB': 'N', 'atpG': 'N', 'dnaJ': 'N', 'flgD': 'N', 'gltA': 'N', 'sucD': 'N', 'tnaA': 'N', 'ygcE': 'N', 'yhdM': 'N', 'ibpB': 'N', 'yfaD': 'N', 'hupB': 'N', 'pspA': 'N', 'asnA': 'N', 'atpD': 'N', 'nmpC': 'N', 'icdA': 'N', 'lacA': 'N', 'yheI': 'N', 'aceB': 'N', 'lacY': 'N', 'b1963': 'N', 'dnaK': 'N', 'folK': 'N', 'ycgX': 'N', 'lacZ': 'N', 'nuoM': 'N', 'dnaG': 'N', 'b1583': 'N', 'mopB': 'N', 'yaeM': 'N', 'ftsJ': 'N'}
INFO:pgmpy: Datatype (N=numerical, C=Categorical Unordered, O=Categorical Ordered) inferred from data:
 {'b1191': 'N', 'cspG': 'N', 'eutG': 'N', 'fixC': 'N', 'cspA': 'N', 'yecO': 'N', 'yedE': 'N', 'sucA': 'N', 'cchB': 'N', 'yceP': 'N', 'ygbD': 'N', 'yjbO': 'N', 'yfiA': 'N', 'lpdA': 'N', 'pspB': 'N', 'atpG': 'N', 'dnaJ': 'N', 'flgD': 'N', 'gltA': 'N', 'sucD': 'N', 'tnaA': 'N', 'ygcE': 'N', 'yhdM': 'N', 'ibpB': 'N', 'yfaD': 'N', 'hupB': 'N', 'pspA': 'N', 'asnA': 'N', 'atpD': 'N', 'nmpC': 'N', 'icdA': 'N', 'lacA': 'N', 'yheI': 'N', 'aceB': 'N', 'lacY': 'N', 'b1963': 'N', 'dnaK': 'N', 'folK': 'N', 'ycgX': 'N', 'lacZ': 'N', 'nuoM': 'N', 'dnaG': 'N', 'b1583': 'N', 'mopB': 'N', 'yaeM': 'N', 'ftsJ': 'N'}
100%|██████████| 100/100 [00:59<00:00,  1.67it/s]

F1-score for the model skeleton:  0.09411764705882353

To save time, we set a small `max_iter` above, therefore the F1 score is low. Feel free to try larger `max_iter` on a smaller model.